/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package gui;

import dto.Cliente;
import java.awt.Color;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.border.LineBorder;

/**
 *
 * @author USUARIO
 */
public class DialogoAlta extends java.awt.Dialog {

    //referencia a padre 
    private PantallaPrincipal pantallaPrincipal;

    /**
     * Creates new form DialogoAlta
     */
    public DialogoAlta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        pantallaPrincipal = (PantallaPrincipal) parent;

        JSpinner.DateEditor editor = new JSpinner.DateEditor(spinnerFechaAlta, "dd/MM/yyyy");
        spinnerFechaAlta.setEditor(editor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jtfApellidos = new javax.swing.JTextField();
        spinnerFechaAlta = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jcbProvincia = new javax.swing.JComboBox<>();
        jButtonAlta = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monospaced", 2, 12)); // NOI18N
        jLabel1.setText("NOMBRE");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 80, 30));

        jLabel2.setFont(new java.awt.Font("Monospaced", 2, 12)); // NOI18N
        jLabel2.setText("APELLIDOS");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 30));

        jLabel3.setFont(new java.awt.Font("Monospaced", 2, 12)); // NOI18N
        jLabel3.setText("FECHA DE ALTA");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 40));

        jtfNombre.setFont(new java.awt.Font("Monospaced", 2, 12)); // NOI18N
        jtfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombreActionPerformed(evt);
            }
        });
        add(jtfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 240, -1));

        jtfApellidos.setFont(new java.awt.Font("Monospaced", 2, 12)); // NOI18N
        add(jtfApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 240, -1));

        spinnerFechaAlta.setFont(new java.awt.Font("Monospaced", 2, 12)); // NOI18N
        spinnerFechaAlta.setModel(new javax.swing.SpinnerDateModel());
        add(spinnerFechaAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 260, 20));

        jLabel4.setFont(new java.awt.Font("Monospaced", 2, 12)); // NOI18N
        jLabel4.setText("PROVINCIA");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 30));

        jcbProvincia.setFont(new java.awt.Font("Monospaced", 2, 12)); // NOI18N
        jcbProvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asturias", "Cantabria", "Leon" }));
        add(jcbProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 260, -1));

        jButtonAlta.setBackground(new java.awt.Color(153, 153, 255));
        jButtonAlta.setFont(new java.awt.Font("Monospaced", 2, 12)); // NOI18N
        jButtonAlta.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAlta.setText("ALTA");
        jButtonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaActionPerformed(evt);
            }
        });
        add(jButtonAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Monospaced", 2, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ALTA DE USUARIO");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 400, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jtfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreActionPerformed

    private void jButtonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaActionPerformed
        // TODO add your handling code here:
        String nombre = jtfNombre.getText();
        String apellidos = jtfApellidos.getText();
        Date fechaAlta = (Date) spinnerFechaAlta.getValue(); //casteos
        String provincia = (String) jcbProvincia.getSelectedItem(); //casteos

        //validacion de datos
        if (!nombre.isEmpty() && !apellidos.isEmpty()) {
            Cliente cliente = new Cliente(nombre, apellidos, fechaAlta, provincia);
            pantallaPrincipal.anadirCliente(cliente);

            dispose();
        } else {
            if (nombre.isEmpty()) {
                JOptionPane.showMessageDialog(this, "el campo ''NOMBRE'' ES OBLIGATORIO"); 

                //para indicarle a que campo ir 
                jtfNombre.requestFocus();

            } else if (apellidos.isEmpty()) {
                JOptionPane.showMessageDialog(this, "el campo ''APELLIDOS'' ES OBLIGATORIO");
                jtfApellidos.requestFocus();
            }

        }
        //creacion del objeto


    }//GEN-LAST:event_jButtonAltaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> jcbProvincia;
    private javax.swing.JTextField jtfApellidos;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JSpinner spinnerFechaAlta;
    // End of variables declaration//GEN-END:variables
}
