/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.table.DefaultTableModel;
import dto.Cliente;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author USUARIO
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        //titulo de la ventana
        this.setTitle("Gestion de clientes");
        //icono de ventana y de app
        ImageIcon icon = new ImageIcon(getClass().getResource("/IMG/logo.png"));
        this.setIconImage(icon.getImage());
        initComponents();
        inicializarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        clientes = new javax.swing.JTable();
        btnEliminarCliente = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfFiltrarNombre = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        Clientes = new javax.swing.JMenu();
        alta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        clientes.setBackground(new java.awt.Color(102, 102, 255));
        clientes.setFont(new java.awt.Font("Monospaced", 2, 12)); // NOI18N
        clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(clientes);

        btnEliminarCliente.setBackground(new java.awt.Color(255, 102, 102));
        btnEliminarCliente.setFont(new java.awt.Font("Monospaced", 2, 12)); // NOI18N
        btnEliminarCliente.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarCliente.setText("Eliminar cliente");
        btnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClienteActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Monospaced", 2, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Cargar datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setFont(new java.awt.Font("Monospaced", 2, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Guardar datos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Monospaced", 2, 12)); // NOI18N
        jLabel1.setText("Filtrar por nombre de cliente:");

        tfFiltrarNombre.setFont(new java.awt.Font("Monospaced", 2, 12)); // NOI18N
        tfFiltrarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFiltrarNombreActionPerformed(evt);
            }
        });
        tfFiltrarNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfFiltrarNombreKeyReleased(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(0, 153, 153));

        Clientes.setBackground(new java.awt.Color(102, 102, 255));
        Clientes.setText("Clientes");

        alta.setText("ALTA...");
        alta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaActionPerformed(evt);
            }
        });
        Clientes.add(alta);

        jMenuBar1.add(Clientes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfFiltrarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 27, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarCliente)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfFiltrarNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(btnEliminarCliente))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void altaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaActionPerformed
        // TODO add your handling code here:
        DialogoAlta dialogoAlta = new DialogoAlta(this, true);
        dialogoAlta.setSize(500, 500); // Dale un tamaño explícito para probar
        //dialogoAlta.setLocationRelativeTo(this); // Centrarlo
        dialogoAlta.setVisible(true);
    }//GEN-LAST:event_altaActionPerformed

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed
        // TODO add your handling code here:
        // Obtenemos el modelo de la tabla
        DefaultTableModel dtm = (DefaultTableModel) clientes.getModel();

        // Obtenemos el índice de la fila seleccionada
        int filaSeleccionada = clientes.getSelectedRow();

        // Verificar si hay una fila seleccionada
        if (filaSeleccionada == -1) {
            // Si no hay selección, mostrar mensaje de advertencia
            JOptionPane.showMessageDialog(this,
                    "Por favor, selecciona una fila para eliminar.",
                    "Sin selección",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            // Confirmación opcional
            int confirmar = JOptionPane.showConfirmDialog(this,
                    "¿Estás seguro de que deseas eliminar este cliente?",
                    "Confirmar eliminación",
                    JOptionPane.YES_NO_OPTION);

            if (confirmar == JOptionPane.YES_OPTION) {
                // 4. Eliminar de la tabla
                dtm.removeRow(filaSeleccionada);

                // 5. Opcional: Eliminar de tu lista lógica de objetos si la tienes
                // listaObjetos.remove(filaSeleccionada);
                JOptionPane.showMessageDialog(this, "Cliente eliminado correctamente.");
            }
        }
    }//GEN-LAST:event_btnEliminarClienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) clientes.getModel();

        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream("clientes.dat"))) {
            // Leemos el objeto
            Vector dataVector = (Vector) ois.readObject();

            // Limpiamos la tabla antes de cargar
            dtm.setRowCount(0);

            // Añadimos las filas una a una
            for (Object row : dataVector) {
                dtm.addRow((Vector) row);
            }

            JOptionPane.showMessageDialog(this, "Datos cargados correctamente.");
        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "No se encontró el archivo de datos.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) clientes.getModel();

        try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("clientes.dat"))) {
            // Guardamos los datos de la tabla)
            oos.writeObject(dtm.getDataVector());
            JOptionPane.showMessageDialog(this, "Datos guardados correctamente en clientes.dat");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tfFiltrarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFiltrarNombreActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tfFiltrarNombreActionPerformed

    private void tfFiltrarNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFiltrarNombreKeyReleased
        // TODO add your handling code here:
        // 1. Obtenemos el modelo de la tabla y su ordenador
        DefaultTableModel dtm = (DefaultTableModel) clientes.getModel();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(dtm);
        clientes.setRowSorter(trs);

        // 2. Aplicamos el filtro usando el texto que hay en el campo
        // El "0" indica que busque en la primera columna (Nombre)
        trs.setRowFilter(RowFilter.regexFilter("(?i)" + tfFiltrarNombre.getText(), 0));
    }//GEN-LAST:event_tfFiltrarNombreKeyReleased

    private void inicializarTabla() {
        // 1. Creamos el modelo sobreescribiendo el método getColumnClass
        DefaultTableModel dtm = new DefaultTableModel() {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                // Esto ayuda al ordenador a saber qué tipo de datos hay
                if (columnIndex == 2) {
                    return String.class;
                }
                return Object.class;
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Opcional: hace que la tabla no se pueda editar escribiendo encima
            }
        };

        // 2. Configuramos las columnas
        dtm.setColumnIdentifiers(new String[]{"Nombre", "Apellidos", "Fecha Alta", "Provincia"});

        // 3. Asignamos el modelo a la JTable
        clientes.setModel(dtm);

        // 4. ACTIVIDAD 5: Habilitamos la ordenación automática
        // Al hacer clic en los encabezados los datos se ordenarán
        clientes.setAutoCreateRowSorter(true);
    }

    public void anadirCliente(Cliente cliente) {
        DefaultTableModel dtm = (DefaultTableModel) clientes.getModel();
        dtm.addRow(cliente.toArrayString());
    }

    //metodo para filtrar cliente
    private void filtrarNombre() {
        // 1. Obtenemos el sorter de la tabla
        TableRowSorter<TableModel> sorter = (TableRowSorter<TableModel>) clientes.getRowSorter();

        // 2. Si el sorter no existe (porque no se inicializó), lo creamos
        if (sorter == null) {
            sorter = new TableRowSorter<>(clientes.getModel());
            clientes.setRowSorter(sorter);
        }

        // 3. Aplicamos el filtro:
        // El primer parámetro es el texto a buscar.
        // El segundo es el índice de la columna (0 es "Nombre").
        // (?i) hace que no importe si son mayúsculas o minúsculas.
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + tfFiltrarNombre.getText(), 0));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Clientes;
    private javax.swing.JMenuItem alta;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JTable clientes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfFiltrarNombre;
    // End of variables declaration//GEN-END:variables
}
